baseurl = "https://example.com/"
title = "Andres Otarola - Software Engineer"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[taxonomies]
  series = "series"

[params]
    author = "Andres Otarola - Software Engineer"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        “When you don't create things, you become defined by your tastes rather than ability. Your tastes only narrow & exclude people. so create.”
― Why The Lucky Stiff

    """
    publicationYear = "2019"
    listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

#[[menu.main]]
#    name = "Blog"
#    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
#    url = "/blog/"
#    weight = 10

[[menu.main]]
    name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/_aotarola_"
    weight = 20

[[menu.main]]
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/aotarola"
    weight = 30

[[menu.main]]
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:andres@otarola.me"
    weight = 40
