version: 2
jobs:
   build:
     docker:
       # use custom image with hugo & firebase-tools pre-installed.
       - image: aotarola/personal-website:2019-04-06
     steps:
       # checkout git repo and theme submodules
       - checkout
       - run: git submodule sync
       - run: git submodule update --init
       - run:
            name: Build static files
            command: hugo
       - run:
            name: Deploy to firebase
            command: firebase --project "$FIREBASE_PROJECTID" deploy --token "$FIREBASE_TOKEN"

